### ISSUE TITLE
Improve error reporting from processes

### ISSUE THREAD

**Issue by huard** [bird-house/finch#129]
## Description

It would be useful for debugging to get more informative messages than "process failed". 
Can we pass a traceback where potentially sensitive information would be hidden ?

**Comment by fmigneault** [comment]
@huard 
If `process._handler` methods where placed in a try/except block, we could provide information based on the caught exception details to the pywps response to have more traceback. 
The biggest issue is about figuring out which amount of details you would consider as sensitive information, and also where these information could be leaked from. 

Even doing a simple dump of the exception message as string could leak details such as "file X/Y/Z not found", which shows server infrastructure details or maybe private file details.
I think the best is to place multiple try/except blocks doing gradual steps of the full process, and in each except log some custom message "process failed because of X", but without using any 'object' that could leak info.

**Comment by cehbrecht** [comment]
You can use the `ProcessError` exception in pywps:
https://pywps.readthedocs.io/en/4.2.4/process.html#process-exceptions

There is also an example in Emu:
https://github.com/bird-house/emu/blob/master/emu/processes/wps_error.py

This exception makes sure that the exception text is "readable"  ... in debug mode you can also see tracebacks.

**Comment by huard** [comment]
Thanks @cehbrecht for this, I had forgotten about it. 

@fmigneault The suggestion of having try/except statement is used in other birds (flyingpigeon, raven), but my experience is that we're rarely successful in anticipating how processes fail. So what happens is that I needed to remove the try/except, reproduce the error locally and then use the traceback to find the root cause. 

@cehbrecht suggestion to use ProcessError and debug mode should be tried. Do we have a log of failed requests from the production server ? This would allow us to to replicate them in debug mode. 

Another idea would be to parse the traceback and somehow remove sensitive information. Not clear what this entails.

**Comment by fmigneault** [comment]
> Another idea would be to parse the traceback and somehow remove sensitive information. Not clear what this entails. 

This is asking for a leak, very hard to provide enough information without giving too much at the same time, especially for exception raised for unknown source. 

ProcessError can be tested, but since it limits by default to 144 characters, it is not much more verbose than regular exception message, except for the extra validation of invalid chars.

**Comment by huard** [comment]
@fmigneault Ok, so still not clear how to go forward. Let's keep thinking about this.

**Comment by MatProv** [comment]
@huard In order to make some kind of prod request shadowing in the debug environment we could log request at proxy level (ex: nginx). Of course, that doesn't solve the security flaws that @fmigneault outlines related to log sanitization and leaks. All parameters would be dump, that way failed requests are easily replicable. That's, of course, subject to deeper compliance investigation.

**Comment by huard** [comment]
@MatProv Interesting, we should probably open another PR to deal with these two issues separately: 
1. Making Finch error messages more informative for users
2. Setup to easily reproduce failures in a debugging environment for developers

**Comment by huard** [comment]
@tlvu You've been faced multiple times with non-obvious errors, could you explore what is missing (Finch, PyWPS) so that errors raise meaningful information about where errors come from and what can users do to fix it? For example, some errors are due to user input, while others are due to the infrastructure itself. At the moment, it's not clear which is which, so users wonder if they did something wrong.
