### ISSUE TITLE
Add support for pydap data store urls

### ISSUE THREAD

**Issue by huard** [bird-house/finch#20]
## Description

To support server-side DAP subsetting, we need to be able to open data store using the xarray pydap backend. That means doing something like: 
```
store = xr.backends.PydapDataStore.open(url) 
ds = xr.open_dataset(store)
```
instead of just  `ds = xr.open_dataset(url)`.

where `url` can be something like `<path>.nc?pr[0:1:5][0:1:2][0:1:3]'

**Comment by davidcaron** [comment]
I could be wrong, but I think that when installed properly, the current netcdf backend can do server-side subsetting?

I explored this to add the bccaqv2 subsetting process, and I did run into some issues, but I found out that it was due to my installation of netcdf4. I was using the netcdf4 package from pypi, and it worked when I installed from conda. It could have been an incompatible version between libnetcdf and the python package, or a feature that wasn't added when compiling, I'm not sure.

I can launch the process on multiple files, requesting for a small area and the dataset is not downloaded entirely, just this area.

Maybe I don't understand your issue, but my work is in the development branch.

**Comment by huard** [comment]
No, you're right, it works. I experimented yesterday and I think it I came to the conclusion that it didn't work when I added .dods at the end of the file name. With the syntax above, it works out of the box. 

I'll document it in the notebook for future reference and then close the issue. 

The backend only supports index-based subsetting though. It would be nice in the future to look at a richer syntax (coordinate-based) 
https://www.unidata.ucar.edu/software/thredds/v4.5/netcdf-java/reference/stream/CdmRemote.html

**Comment by davidcaron** [comment]
I think I understand what you were trying to do. I didn't know about constraint expressions in the opendap protocol (for reference: https://opendap.github.io/documentation/UserGuideComprehensive.html#Constraint_Expressions)

And I think you're right, the netcdf4 python library doesn't support them.

**Comment by huard** [comment]
```
import threddsclient
url_thredds = 'https://pavics.ouranos.ca/thredds/catalog/birdhouse/nrcan/nrcan_canada_daily_v2/pr/catalog.html'
ncfiles = [ds for ds in threddsclient.crawl(url_thredds) if 'pr' in ds.name]
fn = ncfiles[0].opendap_url()
o = wps.cdd(fn+'?pr[0:1:3000][0:1:2][0:1:2]')
```

**Comment by huard** [comment]
Note that this won't work out of the box since the DAP protocol does not pass the metadata information about the coordinates. So when creating a local data from the DAP subset. there are no attributes for time, no encoding, and xclim doesn't work (it needs to make sure data is daily). So is there a way to tell TDS to include coordinate metadata in its response ?

**Comment by huard** [comment]
See https://github.com/pydap/pydap/issues/198

**Comment by huard** [comment]
All coordinate variables should be included in the request, e.g.
```
o = wps.cdd(fn+'?pr[0:1:3000][0:1:2][0:1:2],time[1:1:3000]')
```
So there is nothing to do server-side, it's just a matter of documenting how this works.
