### ISSUE TITLE
Processes using two variables (tasmax + tasmin) such as heat_wave_frequency fails

### ISSUE THREAD

**Issue by ldperron** [bird-house/finch#228]
## Description

When running ensemble_grid_point_heat_wave_frequency, the process ends with an exception: KeyError 'tasmax' on finch/processes/ensemble_utils.py in compute_intermediate_variables at line 469.

After debbuging, I noticed that make_file_groups doesn't work as expected because all the files in files_list has a tempfile.mkstemp characters in its name, so the grouping is not being performed. The mkstemp is being called by resource._build_file_name(resource.url) because the output files are being created (with zero bytes) in the work directory before the subset is done. 

## Environment

* Finch version used, if any: birdhouse/finch:version-0.8.2 docker image

## Steps to Reproduce

```
Run ensemble_grid_point_heat_wave_frequency with finch deployed to use threeds as data source.
```

**Comment by huard** [comment]
I'll need some help on this one. The code's logic is relying on filenames, and pywps messes with filenames in a kind of non-predictable way. 

One solution is to `split("_") the file names and compare the first `[:-1]` items. The problem is that if there are no mkstemp suffix, then we may be grouping things that should not.

**Comment by aulemahal** [comment]
As far as I understand, this is due to this line:
https://github.com/bird-house/finch/blob/a922d8c036fc74b5154900337e1f27fa9e849c3b/finch/processes/subset.py#L32
This  `_build_file_name` transforms the URL to a filename but if that file name is aready taken, it injects randomness.

Why is the file name already taken if we are using url, you say? Because : 
https://github.com/bird-house/finch/blob/a922d8c036fc74b5154900337e1f27fa9e849c3b/finch/processes/subset.py#L85
and
https://github.com/geopython/pywps/blob/7839f5276ced486a8b7f83379e919fb05273b4e7/pywps/inout/basic.py#L537-L539
As they say : lol. We are downloading the file in the sole goal of printing it's name in the log.

But, nonobstant all this,  the filename we create in top code is the not the filename we will use. `make_subset_file_name` ends with:
https://github.com/bird-house/finch/blob/a922d8c036fc74b5154900337e1f27fa9e849c3b/finch/processes/subset.py#L36
i.e.: the path we ask pywps to generate is transformed with an added `_sub` prefix.

Finch assumes the inputs all have different names, so that this `_sub` prefix is always sufficient to distinguish the raw from the subsetted and there will be no duplicates.

I am preparing a PR where I'll remove this treacherous log call and avoid the randomness injection when files are urls.
