### ISSUE TITLE
Empty zip file using subset_bccaqv2

### ISSUE THREAD

**Issue by huard** [bird-house/finch#24]
## Description

See branch bccaqv2_nb for notebook example of download. The output file is empty.

**Comment by davidcaron** [comment]
I see you have `lon0=282, lon1=287`, it works when I enter negative values for the longitude `lon0=-78, lon1=-73`.

Should the xclim subset function handle both? 

I'll explore a bit more.

We should raise an error when the slice returns no data instead of returning 'success' with an empty zip file...

**Comment by davidcaron** [comment]
For demonstration purposes, I think you should take a smaller subset... for example, this takes a little more than 5 minutes to process:

resp = wps.subset_ensemble_bccaqv2('rcp85', 'tasmin', lon0=-78, lon1=-77, lat0=43, lat1=44, y0=1980, y1=1980)

**Comment by huard** [comment]
Ok, please change the nb as you see fit. 

I've made a PR to support this case in xclim. https://github.com/Ouranosinc/xclim/pull/203

The process default for lon1 is 360, so I assumed the scale was from 0 to 360.

**Comment by davidcaron** [comment]
Great, I'll do that and test for values between 0 and 360 when that PR is merged.

**Comment by huard** [comment]
Merged.
