### ISSUE TITLE
Allow ensemble processes to return the dataset with individual realizations

### ISSUE THREAD

**Issue by tlogan2000** [bird-house/finch#270]
## Description
For climatedata.ca users have expressed interest of being able to calculate indicators for individual model runs.  This could potentially be done by calling a large number individual finch processes but in my mind the simplest method forward would be to add a `calculate_percentiles` flag (default = True) to the ensemble_utils calls here : https://github.com/bird-house/finch/blob/38b3e322c140c22a6795e686f62809daafe9dd7c/finch/processes/ensemble_utils.py#L346

ideally we could also make use of the `create_ensemble()`  realizations parameter to add simulation ids as the realizations coordinate https://xclim.readthedocs.io/en/stable/xclim.ensembles.html#xclim.ensembles._base.create_ensemble

**Comment by aulemahal** [comment]
May suggest an alternative : allow to pass `ensemble_percentiles="None"` or just to leave it empty ? This way we don't add another parameter and we don't get the ambiguous situation with `ensemble_percentiles="10,50,90", calculate_percentiles=False"`.

**Comment by tlogan2000** [comment]
Yes makes more sense

**Comment by aulemahal** [comment]
This is not as easy as it seems...
The valid information about the dataset is in the filename of the input and parsed by the `Dataset` class. However, from then on we only work with file lists. We either have to guess again this realization name from the final file names or try to pass the information along. I'm trying to hack some global attributes for the second idea, I'll let you know how it goes.

Otherwise, for the "long term goals we never have time to implement" category, I would add "use catalogs internally".

**Comment by tlogan2000** [comment]
@aulemahal  if `create_ensemble()`  receives something like `realizations = [f.stem for f in filelist]`  I think that would satisfy the need for now ... basically would like to ensure some provenance info of which run is which
