### ISSUE TITLE
Increase options of time aggregation / frequency 

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/finch#70]
include option `all` for a calculation over the entire file and/or multiple file dataset

Here are eggshell `time_group`. 
https://github.com/bird-house/eggshell/blob/master/eggshell/nc/ocg_utils.py#L9

Suggestion: keep CMIP/CORDEX file convention 'yr', instead of 'YS'

Be careful with fileend and e.g. winter aggregation (DEC, JAN, FEB). values might be in two seperated files

**Comment by aulemahal** [comment]
Closing because:
-  CMIP conventions for frequencies are incomplete in regard to what finch needs. `yr` is equivalent to `YS` but also to `AS-JUL` or `AS-NOV`, which is why we'll stick to pandas' conventions.
- I think xclim's indexer, which will be available in most indicators in the next finch, answers the last issue regarding winter aggregation. 
- Finch doesn't concatenate files. It won't understand a dataset divided temporally in multiple files. If we want this option, we should open a new issue for this specifically.
