### ISSUE TITLE
Average over shape process

### ISSUE THREAD

**Issue by huard** [bird-house/finch#98]
## Description

Given one or multiple polygons and a netCDF file, compute the spatial average (area-weighted) over each region and store along a new "geometry" dimension.

Might require to pass a file storing the cell area for accurate computations.

**Comment by richardarsenault** [comment]
@huard , this is in finch, but we now have a basic averaging method using rioxarray to do simple averaging at the catchment scale. Is this something that has advanced and/or reasonable to think that we can get it rolled-out in the next 3 months?

**Comment by huard** [comment]
Yes, it's part of my master plan. Will probably use new functionality just released in xESMF however. Once the weights are computed, this is really fast. See https://pangeo-xesmf.readthedocs.io/en/latest/notebooks/Spatial_Averaging.html

- [x] Implement in xESMF
- [ ] Wrap in clisops https://github.com/roocs/clisops/issues/38
- [ ] Wrap in finch
- [ ] Use in raven workflows

**Comment by rsignell-usgs** [comment]
@huard is there a notebook that demonstrates this capability I could use for a demo?

**Comment by huard** [comment]
https://pavics-sdi.readthedocs.io/en/latest/notebooks/regridding.html#Fourth-example-:-Averaging-over-polygons
https://pangeo-xesmf.readthedocs.io/en/latest/notebooks/Spatial_Averaging.html

**Comment by rsignell-usgs** [comment]
@huard , Is there a python example that would make the polygon request and retrieve the output using this new Finch WPS service?

Or am I not understanding the capabilities?

**Comment by huard** [comment]
@aulemahal I don't think that apart from the unit test, we've gotten there yet, correct ? 

@rsignell-usgs Yes, this is correct. I've created an issue to do this. #165 We probably won't be able to get this done until April though. If you want to try your hand, 
1. install the birdy client: https://github.com/bird-house/birdy
2. connect to the finch server and call the `average_polygon` method:
```
from birdy import WPSClient
url = 'https://pavics.ouranos.ca/twitcher/ows/proxy/finch/wps'
wps = WPSClient(url)
wps.average_polygon?
```

**Comment by aulemahal** [comment]
True, there is no example of the use of this process.

**Comment by aulemahal** [comment]
Oh haha, not a real example, but I had an issue with `subset_polygon` here : https://github.com/bird-house/finch/issues/153#issue-817514044
If I coded this correctly, change `subset` to `average` and you have a minimal example.

**Comment by rsignell-usgs** [comment]
@huard and @aulemahal, I gave it a try, and was able to submit and process a non-polygon request, but failing with polygon request.   I'm sure it's user error:
https://nbviewer.jupyter.org/gist/rsignell-usgs/10059fde7b80d8c29f962505ab024b10

**Comment by huard** [comment]
Try with an absolute file name for the geojson polygon. Otherwise, the client will assume you're passing the geojson object as a string representation. The client could probably be made smarter eventually...

**Comment by rsignell-usgs** [comment]
@huard , I tried 
https://nbviewer.jupyter.org/gist/rsignell-usgs/fa40eea834a48963b5fe2a02feda824b
using the full path name (cell [9]) , and also passing the JSON as string (cell [13]), but couldn't get either to work.  

I'm not sure what else to try, help appreciated!

**Comment by huard** [comment]
The error message suggests that the connection was dropped, so I'll offer a guess. 

PyWPS supports two access mechanisms: sync and async. By default, the birdy client uses sync. sync processes are time-limited, if the server doesn't respond fast enough, the request is just dropped. My guess here is that the tolerance and the size of the polygon make the request fairly compute intensive. You could thus try either to: 

1. limit the computation time by increasing the polygon simplification tolerance (e.g. to .1). On my laptop, this reduces the compute time from 4 minutes to a few seconds. 
2. launch the process asynchronously, (instantiate the client with `wps = WPSClient(pavics_url, progress=True)`)

If this is indeed the problem, a more informative error message would definitely help.

**Comment by rsignell-usgs** [comment]
I tried increasing the polygon tolerance to 0.1 but it still failed. 
I think I am already running async because I successfully used this notebook to access the `dry_days` service, which produces a netcdf file remotely, which I then could access.   

But could the problem be that the WPS service was having a temporary problem?

Today I tried running the same `dry_days` query that worked a few days ago, and it starts, but doesn't complete:
![2021-03-29_10-40-54](https://user-images.githubusercontent.com/1872600/112854532-f3c3ba80-907b-11eb-920c-573f88a3595e.png)

**Comment by rsignell-usgs** [comment]
The above was with:
```
dap_url = 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/flyingpigeon/cmip3/pr.sresa2.miub_echo_g.run1.atm.da.nc'
```

**Comment by huard** [comment]
Thanks for your patience, will report the error to our sysadmin.

**Comment by rsignell-usgs** [comment]
I tried a few minutes ago, and didn't get the 500.
But after failing the above, I'm now getting a 500 error again.

**Comment by rsignell-usgs** [comment]
@huard , are **you** able to run the above 5 lines of code?

**Comment by Zeitsperre** [comment]
I just tried it myself, Code 500 Server error for Finch is what I'm seeing.

**Comment by aulemahal** [comment]
I can confirm, Error 500 when using pavics, but passes with @tlvu's VM.
I'm on it, trying to figure out the issue, but it's hard since it doesn't happen in the VM and the logs don't give you information on what request triggers the errors.

**Comment by Zeitsperre** [comment]
@aulemahal is the version of `birdy` different on the test VM? I have 0.7.0 for PAVICS.

**Comment by aulemahal** [comment]
I'm testing on pavics, but calling finch on the VM, so birdy is the same. And finch is at 0.7.1 on both sides...

**Comment by tlvu** [comment]
@Zeitsperre @aulemahal can you guys use the official Jupyter environment on PAVICS to reproduce the error?  If we do not have a reproducible environment, it's hard to reproduce the problem.

**Comment by aulemahal** [comment]
@rsignell-usgs It seems that the error was on the server side, the finch server was getting too crowded because of the use of `progress=True`.

The main WPS server should **never** be used with `progress=True`.
But we also have an "async" finch here : https://pavics.ouranos.ca/twitcher/ows/proxy/finchasync/wps, this one can safely be used with that option.

I did not know this before! This should fix the `dry_days` problem. I'm going back to the average shape one...

**Comment by tlvu** [comment]
> @huard , I tried
> https://nbviewer.jupyter.org/gist/rsignell-usgs/fa40eea834a48963b5fe2a02feda824b
> using the full path name (cell [9]) , and also passing the JSON as string (cell [13]), but couldn't get either to work.
> 
> I'm not sure what else to try, help appreciated!

@rsignell-usgs 

Could you provide `/home/jovyan/shared/users/rsignell/notebooks/WPS/output.geojson` used in your notebook https://nbviewer.jupyter.org/gist/rsignell-usgs/fa40eea834a48963b5fe2a02feda824b?  Trying to reproduce the error in your notebook.

However, as @aulemahal rightfully point out, avoid using `progress=True` with the main WPS server.

For `progress=True` please use  https://pavics.ouranos.ca/twitcher/ows/proxy/finchasync/wps instead.  The root cause is this bug https://github.com/bird-house/finch/issues/121 which really is on PyWPS library side.

**Comment by tlvu** [comment]
> Could you provide `/home/jovyan/shared/users/rsignell/notebooks/WPS/output.geojson` used in your notebook https://nbviewer.jupyter.org/gist/rsignell-usgs/fa40eea834a48963b5fe2a02feda824b? Trying to reproduce the error in your notebook.

Sorry, read the notebook too fast.  Didn't notice `output.geojson` was created in cell 7.

**Comment by rsignell-usgs** [comment]
@tlvu, were you able to reproduce?

**Comment by rsignell-usgs** [comment]
I tried with the async version of the server.   The `dry_days` process worked, but I couldn't get far with `average_polygon`.  

Here's my current notebook:
https://nbviewer.jupyter.org/gist/rsignell-usgs/109c47f1a792a658e9164c1240b6c49a

**Comment by aulemahal** [comment]
@rsignell-usgs  I am indeed investiguating the issue. It happens on both prod and "dev" servers, but not locally, so it may have to do with the interaction between all the web server layers. I think there is also an error on the logging side that makes it even harder to debug. I'm trying to fix that first.

**Comment by aulemahal** [comment]
@rsignell-usgs @huard  Ok, all this work for the conclusion we kinda already knew:
I was able to successfully average using a local shape!

The first reason the tasks where failing is indeed the size of the input. Our finch seems to accept only inputs below 3 Mo. `output.geojson` as my example creates it is 13 Mo. I simplified the polygon upstream to tolerances of 0.001 (yielding 2.2 Mo, and 0.01 : 800 Ko). The error message is not clear at all "BrokenPipe", but the logs do say `File size for input exceeded. Maximum request size allowed: 3.0 megabytes`.

The second reason is that the non-async finch will timeout because xESMF is slow, especially with large polygons.
The 800 Ko polygon worked successfully on both finches and I seem to be able to use the async version for the 2.2 Mo, but it is very slow (on the dev server). xESMF's polygon parsing is single threaded, so it doesn't scale easily.  Again, this issue was combined with #168, timeout processes pollute the database and block further processes.

Also, the progress reporting is quite poor as we delegated everything to clisops. Even with implementing the averaging function ourselves we would only be able to report once more : when the weights are created, before computing the average itself.

I'll make sure to explain and show the simplification process in my upcoming notebook.

**Comment by rsignell-usgs** [comment]
@aulemahal , thanks for that detective work!    
In addition those issues, there is still some network/security issues/layers that are preventing me from doing *any* successful query, right?

**Comment by aulemahal** [comment]
I think not anymore! Both finches (async and normal) on pavics seem to be running correctly. I just tried:
```
pavics_url = 'https://pavics.ouranos.ca/twitcher/ows/proxy/finch/wps'
wps = WPSClient(pavics_url)
dap_url = 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/flyingpigeon/cmip3/pr.sresa2.miub_echo_g.run1.atm.da.nc'
resp = wps.dry_days(dap_url, thresh='0.1 mm/day', variable='pr')
```
and it works.

**Comment by rsignell-usgs** [comment]
Do you have an `average_polygon` example that works?   That's the one I was struggling with.

**Comment by aulemahal** [comment]
Oh!  Give me 30 minutes.

**Comment by rsignell-usgs** [comment]
Hoping we can make something like cell [13] work in https://gist.github.com/tlvu/f6de3098cad70709fbed990f4e7d61d4

**Comment by aulemahal** [comment]
Here we go:
https://gist.github.com/aulemahal/88343751b99ddc2f0d5a0f07d8f2fdf4

The main trick is to simplify the polygons *before* they are sent to finch. Here I am using `geopandas`, reading the WFS-retrieved polygons directly into it and simplifying before writing to file. Seems that geojsons under 1 Mo will not cause time outs and work with the normal finch instance.
Larger polygons (but under 3 Mo) might work with the async version, but for now my only test hung indefinitely...

@huard  Sadly, I found yet another bug. The current finch behavior is to chunk datasets when they have over 1 000 000 points. However, it chunks _all dimensions_ while the averaging process doesn't support chunking along the spatial dimensions... The testdata we are using here will work, but larger datasets won't.

**Comment by huard** [comment]
Ok, please create issues and tag it with the DACCS label. We'll fix it in the next release. I guess this requires a release of xESMF, clisops and finch ?

**Comment by aulemahal** [comment]
Hum, I don't think it's possible to perform the average with chunks along spatial dimensions, so I don't think we could change xESMF in any meaningful way. Same for clisops, except that clisops has an easier access to the spatial dimensions names. But rechunking on-the-fly without user input isn't very elegant. I really think this is a finch problem.

**Comment by huard** [comment]
ok, easier then !

**Comment by tlvu** [comment]
> Our finch seems to accept only inputs below 3 Mo.

Found out it's the default from PyWPS https://github.com/geopython/pywps/blob/20e1e254a3f7914e555fa89f363d1f6eb5f3895c/pywps/configuration.py#L74

We can override in our Finch, what would be a reasonable value?  Was the default at 3Mb for a reason?

I just set that limit to 20Mb on my dev server if someone wants to try.

**Comment by rsignell-usgs** [comment]
@aulemahal , is there an updated notebook that demonstrates the average over shape process?

**Comment by aulemahal** [comment]
Yes! Here: https://pavics-sdi.readthedocs.io/projects/finch/en/latest/notebooks/subset.html#Averaging-over-polygons
There still some limitations, the first is non-negligeable:
1 - No missing value handling (1 NaN gridcell means the average is NaN), but this is currently being fixed. I suspect it will be integrated in finch this summer.
2 - Often we need to simplify the polygons on the client side. This is in part due to a bug in OWSlib, I have no ETA for a fix...

**Comment by rsignell-usgs** [comment]
Great!  And thanks for the reminders about the limitations --those are important to know!
